export const SHOW_APP_LOADER = "SHOW_LOADER"
export const HIDE__APP_LOADER = "HIDE_LOADER"

export const ADD_APP_MESSAGE = "ADD_APP_MESSAGE"
export const CLEAR_APP_MESSAGE = "CLEAR_APP_MESSAGE"
export const REMOVEALL_APP_MESSAGE = "REMOVEALL_APP_MESSAGE"